### ISSUE TITLE
Disable ssl env variable missing for bulk processor template yaml

### ISSUE THREAD

**Issue by danishjamal104** [openMF/ph-ee-env-template#33]

**Comment by danishjamal104** [comment]
@fynmanoj this is imp.

**Comment by fynmanoj** [comment]
@danishjamal104  Can you add the variables and Send a PR

**Comment by danishjamal104** [comment]
Fixed in #38

**Comment by danishjamal104** [comment]
done

Regards,
Danish Jamal
Github <http://github.com/danishjamal104> | LinkedIn
<https://www.linkedin.com/in/danishjamal104/>
